name: Compatibility Check

on:
  push:
    branches: [ main ]

jobs:
  compatibility-check:
    name: Compatibility Check
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Give permissions for script to run
        run: |
          sudo chmod +x report-test-build.sh
      - name: Run script
        run: ./report-test-build.sh